/**
 * Scala Entity class.
 * Generated by Codini.
 */
package com.seednia.module.core.project.dto;

case class User(
	sid: Long,
	createDt: DateTime,
	modifyCounter: Int,
	lastModifiedDt: DateTime,
	status: Int,
	type: String,
	role: String,
	timeCommitment: Int,
	description: String,
	lastActivityDt: DateTime,
	paramsText: String,
	creatorDto: class,
	projectDto: class,
	userDto: class
 
);

