/**
 * Scala Entity class.
 * Generated by Codini.
 */
package com.seednia.module.core.project.dto;

case class User(
	sid: Long,
	domainId: String,
	createDt: DateTime,
	modifyCounter: Int,
	lastModifiedDt: DateTime,
	uuid: String,
	id: String,
	name: String,
	goal: String,
	description: String,
	successCriteria: String,
	challenges: String,
	planStartDate: DateTime,
	actualStartDate: DateTime,
	planEndDate: DateTime,
	actualEndDate: DateTime,
	lookingFor: Int,
	status: Int,
	privacyLevel: Int,
	numCheers: Int,
	sysStatus: Int,
	requiredSkillTagNamesCsv: String,
	successLevel: Int,
	evaluationPositive: String,
	evaluationNegative: String,
	improvements: String,
	paramsText: String,
	creatorDto: class,
	ownerDto: class,
	categoryDto: class,
	profileImage: class
 
);

