/**
 * Scala Entity class.
 * Generated by Codini.
 */
package com.seednia.module.core.project.dto;

case class User(
	sid: Long,
	createDt: DateTime,
	modifyCounter: Int,
	lastModifiedDt: DateTime,
	weight: Int,
	creatorDto: class
 
);

