<?php
if (!function_exists('to_scala_type')) { 
	function to_scala_type($type)
	{
		$type_mapping = array(
			'bigint' => 'int', 
			'boolean' => 'Boolean', 
			'clob' => 'String', 
			'char' => 'char', 
			'date' => 'Date', 
			'datetime' => 'DateTime', 
			'decimal' => 'Float', 
			'double' => 'Double', 
			'enum' => 'ENUM', 
			'float' => 'Float', 
			'int' => 'Int', 
			'long' => 'Long', 
			'string' => 'String', 
			'short' => 'Short', 
			'text' => 'String', 
			'time' => 'Time', 
			'timestamp' => 'DateTime', 
		);
		return array_key_exists($type, $type_mapping) ? $type_mapping[$type] : $type;
	}
}
?>
/**
 * Scala Entity class.
 * Generated by Codini.
 */
package <?php echo $entity->get_fqns(); ?>;

case class User(
<?php 
$ctr = 0;
$count = sizeof($entity->field_descriptions);
foreach ($entity->field_descriptions as $field_descr) {
	$ctr++; 
	echo "\t" . $field_descr->name . ': ' . to_scala_type($field_descr->type);  
	if ($ctr < $count) 
		echo ',';
	echo "\n";
} 
?> 
);

