/**
 * Scala Entity class.
 * Generated by Codini.
 */
package com.seednia.module.core.quantilize;

case class User(
	sid: Long,
	domainId: String,
	createDt: DateTime,
	modifyCounter: Int,
	lastModifiedDt: DateTime,
	uuid: String,
	name: String,
	description: String,
	creatorDto: ,
	userDto: ,
	projectDto: 
 
);

