/**
 * Scala Entity class.
 * Generated by Codini.
 */
package com.seednia.module.core.quantilize;

case class User(
	sid: Long,
	domainId: String,
	createDt: DateTime,
	modifyCounter: Int,
	lastModifiedDt: DateTime,
	uuid: String,
	note: String,
	startDt: DateTime,
	endDt: DateTime,
	interrupSec: Long,
	durationSec: Long,
	registLocation: String,
	creatorDto: ,
	userDto: ,
	projectDto: ,
	activityTypeDto: 
 
);

